#!/bin/env zsh

up () {
    # TODO: use eval to avoid code repetition
    if command -v setopt &> /dev/null
    then
      setopt local_options NO_NOTIFY NO_MONITOR
      (osascript -e "repeat \"$(( ${1:-1}+1 ))\" times" -e "tell application \"System Events\" to tell process \"Terminal\" to key code 126 using command down" -e "end repeat")
    else
      (osascript -e "repeat \"$(( ${1:-1}+1 ))\" times" -e "tell application \"System Events\" to tell process \"Terminal\" to key code 126 using command down" -e "end repeat" &)
    fi
}
