# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

autoload -Uz compinit
if [ $(date +'%j') != $(stat -f '%Sm' -t '%j' ~/.zcompdump) ]; then
  compinit
else
  compinit -C
fi
setopt CORRECT
setopt CORRECT_ALL

export POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
source $HOME/.dotfiles/.plugins.sh
source $HOME/.dotfiles/prompt.sh
zsh-defer source $HOME/.dotfiles/envvars.sh
zsh-defer source $HOME/.dotfiles/aliases.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
